import type { Project } from './types';

export const projects: Project[] = [
  {
    id: 'ousos-villas',
    name: { ar: 'فلل أسس P122', en: 'OSUS Villas P122' },
    location: { ar: 'الرياض', en: 'Riyadh' },
    contractor: { ar: 'شركة باني المحدودة', en: 'Bani Limited Co.' },
    owner: { ar: 'OSUS', en: 'OSUS' },
    sector: 'commercial',
    year: 2025,
    status: 'completed',
  },
  {
    id: 'othaim-markets',
    name: {
      ar: 'فروع أسواق العثيم بالمنطقة الغربية',
      en: 'Othaim Markets — Western Region Branches',
    },
    location: { ar: 'جدة - مكة', en: 'Jeddah – Makkah' },
    contractor: { ar: 'فابكو للإنشاءات', en: 'FABCO Construction' },
    owner: { ar: 'شركة العثيم القابضة', en: 'Othaim Holding Company' },
    sector: 'commercial',
    year: 2025,
    status: 'completed',
  },
  {
    id: 'national-guard-maintenance',
    name: {
      ar: 'صيانة معسكرات الحرس الوطني',
      en: 'National Guard Camps Maintenance',
    },
    location: { ar: 'الرياض', en: 'Riyadh' },
    contractor: { ar: 'زهرة الصحراء للمقاولات', en: 'Zahret Al-Sahara Con.' },
    owner: { ar: 'قسم صيانة الحرس الوطني', en: 'National Guard Maintenance Section' },
    sector: 'guard',
    year: '2023 — ',
    status: 'ongoing',
  },
  {
    id: 'air-force-hangars',
    name: {
      ar: 'استبدال أبواب الحظائر والمستودعات - القطاع الغربي',
      en: 'Hangar & Warehouse Door Replacement (Western Sector)',
    },
    location: { ar: 'جدة', en: 'Jeddah' },
    owner: { ar: 'القوات الجوية', en: 'Air Force' },
    sector: 'defense',
    year: 2024,
    status: 'completed',
  },
  {
    id: 'arms-center-najran',
    name: {
      ar: 'صيانة الأبواب المنزلقة لمركز التسليح',
      en: 'Arms Center — Sliding Door Maintenance',
    },
    location: { ar: 'نجران', en: 'Najran' },
    owner: { ar: 'القوات البحرية', en: 'Naval Forces' },
    sector: 'defense',
    year: 2024,
    status: 'completed',
  },
  {
    id: 'royal-guard-gharbia',
    name: {
      ar: 'استبدال أبواب جراجات معسكر الحرس الملكي بالغربية',
      en: 'Garage Door Replacement — Royal Guard Camp (Western Sector, Jeddah)',
    },
    location: { ar: 'جدة', en: 'Jeddah' },
    owner: { ar: 'الحرس الملكي', en: 'Royal Guard' },
    sector: 'guard',
    year: 2025,
    status: 'completed',
  },
  {
    id: 'villa-abc-phase-2',
    name: {
      ar: 'استبدال أبواب جراج فلل ABC - المرحلة الثانية',
      en: 'Villa ABC Garage Door Replacement (Phase II)',
    },
    location: { ar: 'الرياض', en: 'Riyadh' },
    owner: { ar: 'القوات البحرية', en: 'Naval Forces' },
    sector: 'defense',
    year: 2024,
    status: 'completed',
  },
  {
    id: 'land-forces-electric-shutters',
    name: {
      ar: 'أبواب شتر رول كهربائية - سلاح الصيانة بالقوات البرية',
      en: 'Electric Roller Shutter Doors — Land Forces Maintenance Corps',
    },
    location: { ar: 'الخرج - رفحا - شرورة - تبوك', en: 'Al-Kharj, Rafha, Sharurah, Tabuk' },
    owner: { ar: 'القوات البرية', en: 'Ground Forces' },
    sector: 'defense',
    year: 2024,
    status: 'completed',
  },
  {
    id: 'mod-sliding-doors-jeddah',
    name: {
      ar: 'فحص وإصلاح واستبدال الأبواب المنزلقة',
      en: 'Inspection, Repair & Replacement of Sliding Doors',
    },
    location: { ar: 'جدة', en: 'Jeddah' },
    owner: { ar: 'وزارة الدفاع', en: 'Ministry of Defense' },
    sector: 'defense',
    year: 2024,
    status: 'completed',
  },
  {
    id: 'royal-guard-rabwa',
    name: {
      ar: 'تحديث واستبدال أبواب جراج معسكر الحرس الملكي بالربوة',
      en: 'Garage Doors Update at the Royal Guard Camp, Rabwa',
    },
    location: { ar: 'الربوة', en: 'Rabwa' },
    owner: { ar: 'الحرس الملكي', en: 'Royal Guard' },
    sector: 'guard',
    year: 2023,
    status: 'completed',
  },
  {
    id: 'madinah-region-sliding-parts',
    name: {
      ar: 'توريد قطع غيار للأبواب المنزلقة',
      en: 'Sliding Door Spare Parts Supply',
    },
    location: { ar: 'الدمام', en: 'Dammam' },
    owner: { ar: 'قيادة منطقة المدينة', en: 'Madinah Region Leadership' },
    sector: 'defense',
    year: 2023,
    status: 'completed',
  },
  {
    id: 'air-defense-hofuf',
    name: {
      ar: 'توريد وتركيب أبواب منزلقة لورش صيانة المركبات',
      en: 'Sliding Doors for Vehicle Maintenance Workshops',
    },
    location: { ar: 'الأحساء', en: 'Al-Hofuf' },
    owner: { ar: 'الدفاع الجوي', en: 'Air Defense Forces' },
    sector: 'defense',
    year: 2023,
    status: 'completed',
  },
  {
    id: 'naval-gharbia-maritime',
    name: {
      ar: 'تجهيز أبواب قسم البحرية',
      en: 'Maritime Department Doors Construction & Equipping',
    },
    location: { ar: 'الغربية', en: 'Gharbia' },
    owner: { ar: 'القوات البحرية', en: 'Naval Forces' },
    sector: 'defense',
    year: 2023,
    status: 'completed',
  },
  {
    id: 'northern-region-transport-cloud',
    name: {
      ar: 'أبواب أمنية لقسم النقل والمعدات',
      en: 'Secure Cloud Doors — Transportation & Equipment Department',
    },
    location: { ar: 'الرياض', en: 'Riyadh' },
    owner: { ar: 'المنطقة الشمالية', en: 'Northern Region' },
    sector: 'defense',
    year: 2023,
    status: 'completed',
  },
  {
    id: 'swcc-jeddah-phase',
    name: {
      ar: 'صيانة الأبواب المنزلقة - محطة جدة',
      en: 'Sliding Door Maintenance — Jeddah Production Phase',
    },
    location: { ar: 'جدة', en: 'Jeddah' },
    owner: { ar: 'المؤسسة العامة لتحلية المياه المالحة', en: 'Saline Water Conversion Corporation' },
    sector: 'utility',
    year: 2023,
    status: 'completed',
  },
  {
    id: 'artillery-wing-403',
    name: {
      ar: 'استبدال أبواب القطع المنزلقة - مبنى 403',
      en: 'Overhead Sectional Doors Replacement — Building 403',
    },
    location: { ar: 'الرياض', en: 'Riyadh' },
    owner: { ar: 'سلاح المدفعية', en: 'Artillery Wing' },
    sector: 'defense',
    year: 2023,
    status: 'completed',
  },
  {
    id: 'border-guard-najran',
    name: {
      ar: 'صيانة وتوريد وتركيب أبواب الرول - مستودعات حرس الحدود بنجران',
      en: 'Roller Door Maintenance / Supply / Installation — Border Guard Najran',
    },
    location: { ar: 'نجران', en: 'Najran' },
    owner: { ar: 'وزارة الداخلية', en: 'Ministry of Interior' },
    sector: 'government',
    year: 2023,
    status: 'completed',
  },
  {
    id: 'medical-warehouses-spares',
    name: {
      ar: 'صيانة المستودعات الطبية وتوريد قطع الغيار',
      en: 'Medical Warehouses — Maintenance & Spare Parts',
    },
    location: { ar: 'المستودعات الطبية', en: 'Medical Warehouses' },
    owner: { ar: 'المستودعات الطبية', en: 'Medical Warehouses' },
    sector: 'government',
    year: 2023,
    status: 'completed',
  },
  {
    id: 'air-defense-institute',
    name: {
      ar: 'إصلاح أبواب القطع - معهد الدفاع الجوي',
      en: 'Overhead Doors Repair — Air Defense Institute',
    },
    location: { ar: 'الرياض', en: 'Riyadh' },
    owner: { ar: 'الدفاع الجوي', en: 'Air Defense Forces' },
    sector: 'defense',
    year: 2023,
    status: 'completed',
  },
  {
    id: 'naval-roller-supply-install',
    name: {
      ar: 'توريد وتركيب باب رول مع موتور سلايد',
      en: 'Roller Door Supply & Install with Slide Motor',
    },
    location: { ar: 'الرياض', en: 'Riyadh' },
    owner: { ar: 'القوات البحرية', en: 'Naval Forces' },
    sector: 'defense',
    year: 2023,
    status: 'completed',
  },
  {
    id: 'air-defense-cloud-motor',
    name: {
      ar: 'تأمين موتور باب لصيانة باب السحب',
      en: 'Door Motor Securing for Cloud Door Maintenance',
    },
    location: { ar: 'الرياض', en: 'Riyadh' },
    owner: { ar: 'الدفاع الجوي', en: 'Air Defense Forces' },
    sector: 'defense',
    year: 2023,
    status: 'completed',
  },
  {
    id: 'strategic-missile-riyadh-water-net',
    name: {
      ar: 'توريد مواد صيانة شبكة المياه - الرياض الموقع 2',
      en: 'Water Network Maintenance Materials — Riyadh Site 2',
    },
    location: { ar: 'الرياض', en: 'Riyadh' },
    owner: { ar: 'قوة الصواريخ الاستراتيجية', en: 'Strategic Missile Force' },
    sector: 'defense',
    year: 2023,
    status: 'completed',
  },
  {
    id: 'air-defense-zipper-door-inspection',
    name: {
      ar: 'فحص وصيانة باب السحب - الدفاع الجوي',
      en: 'Zipper Door Inspection & Maintenance — Air Defense',
    },
    location: { ar: 'جدة', en: 'Jeddah' },
    owner: { ar: 'الدفاع الجوي', en: 'Air Defense Forces' },
    sector: 'defense',
    year: 2023,
    status: 'completed',
  },
  {
    id: 'strategic-missile-rollup-site3',
    name: {
      ar: 'توريد وتركيب أبواب رول - الرياض الموقع 3',
      en: 'Roll-Up Doors Supply & Install — Riyadh Site 3',
    },
    location: { ar: 'الرياض', en: 'Riyadh' },
    owner: { ar: 'قوة الصواريخ الاستراتيجية', en: 'Strategic Missile Force' },
    sector: 'defense',
    year: 2023,
    status: 'completed',
  },
  {
    id: 'carford-spare-parts',
    name: {
      ar: 'قطع غيار أبواب Carford - قاعدة الصيانة والإسناد الفني',
      en: 'Carford Sliding Door Spares — Maintenance & Tech Support Base',
    },
    location: { ar: 'الرياض', en: 'Riyadh' },
    owner: { ar: 'الدفاع الجوي', en: 'Air Defense Forces' },
    sector: 'defense',
    year: 2023,
    status: 'completed',
  },
  {
    id: 'royal-guard-nasiriyah',
    name: {
      ar: 'ترميم واستبدال أبواب جراج معسكر الحرس الملكي بالناصرية',
      en: 'Garage Doors Restoration — Royal Guard Camp Nasiriyah',
    },
    location: { ar: 'الرياض', en: 'Riyadh' },
    owner: { ar: 'الحرس الملكي', en: 'Royal Guard' },
    sector: 'guard',
    year: 2024,
    status: 'completed',
  },
  {
    id: 'fifth-group-sliding-install',
    name: {
      ar: 'توريد وتركيب أبواب منزلقة - المجموعة الخامسة',
      en: 'Sliding Doors Supply & Install — Fifth Group',
    },
    location: { ar: 'الرياض', en: 'Riyadh' },
    owner: { ar: 'الدفاع الجوي', en: 'Air Defense Forces' },
    sector: 'defense',
    year: 2023,
    status: 'completed',
  },
  {
    id: 'air-defense-commissioning',
    name: {
      ar: 'تركيب وتشغيل أبواب منزلقة',
      en: 'Sliding Doors Installation & Commissioning',
    },
    location: { ar: 'الرياض', en: 'Riyadh' },
    owner: { ar: 'الدفاع الجوي', en: 'Air Defense Forces' },
    sector: 'defense',
    year: 2023,
    status: 'completed',
  },
  {
    id: 'jubail-royal-commission',
    name: {
      ar: 'توريد واستبدال كراجات لمرافق الهيئة الملكية والمرافق الحكومية',
      en: 'Garage Supply & Replacement — Royal Commission & Government Facilities',
    },
    location: { ar: 'الجبيل', en: 'Jubail' },
    owner: { ar: 'الهيئة الملكية للجبيل وينبع', en: 'Royal Commission for Jubail & Yanbu' },
    sector: 'government',
    year: '2023–2025',
    status: 'completed',
  },
  {
    id: 'kkmc-transport-shutters',
    name: {
      ar: 'توريد وتركيب أبواب سحاب لقسم النقل والمعدات',
      en: 'Shutter Doors Supply & Install — Transport & Equipment Dept.',
    },
    location: { ar: 'حفر الباطن', en: 'Hafr Al-Batin' },
    owner: { ar: 'مدينة الملك خالد العسكرية', en: 'King Khalid Military City' },
    sector: 'defense',
    year: 2023,
    status: 'completed',
  },
  {
    id: 'strategic-missile-base-511',
    name: {
      ar: 'توريد وتركيب أبواب رول - المدينة السكنية بالقاعدة 511',
      en: 'Roller Doors Supply & Install — Residential City, Base 511',
    },
    location: { ar: 'الرياض', en: 'Riyadh' },
    owner: { ar: 'قوة الصواريخ الاستراتيجية', en: 'Strategic Missile Force' },
    sector: 'defense',
    year: 2024,
    status: 'completed',
  },
  {
    id: 'naval-king-salman-villas',
    name: {
      ar: 'استبدال أبواب الكراج لفلل A-B-C - قاعدة الملك سلمان للإسناد البحري',
      en: 'Villa A-B-C Garage Door Replacement — King Salman Naval Support Base',
    },
    location: { ar: 'الجبيل', en: 'Jubail' },
    owner: { ar: 'القوات البحرية', en: 'Royal Saudi Naval Forces' },
    sector: 'defense',
    year: 2025,
    status: 'completed',
  },
];

export const projectStats = {
  total: projects.length,
  sectors: new Set(projects.map((p) => p.sector)).size,
  yearsActive: new Date().getFullYear() - 2022,
};
